spring:
  application:
    name: test-server

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      profile: dev
      label: main
    bus:
      enabled: true

  config:
    import: "optional:configserver:"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'